Repository FC-Toy-Project-9/Toy_Project2, pull requests merged in 2023-10, with the labels that each got.

#1 테스트 시 H2를 사용하도록 설정 추가
  build.gradle
  src/test/resources/application.yaml
Labels: 🛠️feature

#3 Spring REST Docs 도입
  build.gradle
  src/docs/asciidoc/index.adoc
  src/test/java/com/fc/toy_project2/docs/SampleController.java
  src/test/java/com/fc/toy_project2/docs/SampleControllerDocsTest.java
  src/test/java/com/fc/toy_project2/util/RestDocsConfig.java
  src/test/java/com/fc/toy_project2/util/RestDocsSupport.java
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: 📚document, 🛠️feature

#5 여행 목록 조회, 특정 여행 조회, 여행 정보 수정 API 구현
  src/docs/asciidoc/trip/trip-api.adoc
  src/main/java/com/fc/toy_project2/domain/trip/controller/TripRestController.java
  src/main/java/com/fc/toy_project2/domain/trip/controller/TripRestControllerAdvice.java
  src/main/java/com/fc/toy_project2/domain/trip/dto/request/UpdateTripRequestDTO.java
  src/main/java/com/fc/toy_project2/domain/trip/dto/response/TripResponseDTO.java
  src/main/java/com/fc/toy_project2/domain/trip/entity/Trip.java
  src/main/java/com/fc/toy_project2/domain/trip/exception/TripNotFoundException.java
  src/main/java/com/fc/toy_project2/domain/trip/exception/WrongTripEndDateException.java
  src/main/java/com/fc/toy_project2/domain/trip/exception/WrongTripStartDateException.java
  src/main/java/com/fc/toy_project2/domain/trip/repository/TripRepository.java
  src/main/java/com/fc/toy_project2/domain/trip/service/TripService.java
  src/test/java/com/fc/toy_project2/trip/docs/TripRestControllerDocsTest.java
  src/test/java/com/fc/toy_project2/trip/unit/controller/TripRestControllerTest.java
  src/test/java/com/fc/toy_project2/trip/unit/service/TripServiceTest.java
  src/test/java/com/fc/toy_project2/util/RestDocsSupport.java
  src/test/resources/application.yaml
Labels: 📚document, 🛠️feature, 🧑🏻‍🔧fix, 🚧refactoring

#4 feat: 일시 포맷 기능 구현
  src/main/java/com/fc/toy_project2/global/exception/InvalidDateFormatException.java
  src/main/java/com/fc/toy_project2/global/util/DateTypeFormatterUtil.java
  src/test/java/com/fc/toy_project2/global/util/DateTypeFormatterUtilTest.java
Labels: 🛠️feature

#7 여행 조회, 수정에 ResponseDTO, DateTypeFormatterUtil 도입
  src/main/java/com/fc/toy_project2/domain/trip/controller/TripRestController.java
  src/main/java/com/fc/toy_project2/domain/trip/controller/TripRestControllerAdvice.java
  src/main/java/com/fc/toy_project2/domain/trip/entity/Trip.java
  src/main/java/com/fc/toy_project2/domain/trip/service/TripService.java
Labels: 🚧refactoring

#8 여행 수정 시 날짜 체크 수정
  src/main/java/com/fc/toy_project2/domain/trip/service/TripService.java
Labels: 🧑🏻‍🔧fix

#11 feat&docs: 여행 등록 및 특정 여행 정보 삭제 API Spring REST Docs 적용
  src/docs/asciidoc/trip/trip-api.adoc
  src/test/java/com/fc/toy_project2/trip/docs/TripRestControllerDocsTest.java
Labels: 📚document, 🛠️feature, 🧑🏻‍🔧fix

#13 REST Docs로 만들어진 html 복사 수정
  .gitignore
  build.gradle
Labels: 🧑🏻‍🔧fix

#15 API KEY Secret 설정
  .github/workflows/gradle.yml
Labels: 🛠️feature

#16 Secret 환경 변수 설정 수정
  .github/workflows/gradle.yml
  src/main/resources/application.yaml
  src/test/resources/application.yaml
Labels: 🧑🏻‍🔧fix

#12 특정 여행 삭제 시, 관련 여정 데이터 함께 삭제하도록 수정
  src/main/java/com/fc/toy_project2/domain/trip/entity/Trip.java
Labels: 🧑🏻‍🔧fix

#19 Global Controller Advice 구현
  src/main/java/com/fc/toy_project2/global/exception/GlobalControllerAdvice.java
Labels: 🛠️feature

#21 Invalid Date Format Exception 핸들링
  src/main/java/com/fc/toy_project2/global/exception/GlobalControllerAdvice.java
  src/main/java/com/fc/toy_project2/global/exception/InvalidDateFormatException.java
  src/main/java/com/fc/toy_project2/global/util/DateTypeFormatterUtil.java
Labels: 🛠️feature, 🚧refactoring

#22 Trip API 요청 및 응답 DTO 변수명 및 URI 수정
  src/main/java/com/fc/toy_project2/domain/trip/controller/TripRestController.java
  src/main/java/com/fc/toy_project2/domain/trip/dto/request/UpdateTripRequestDTO.java
  src/main/java/com/fc/toy_project2/domain/trip/dto/response/TripResponseDTO.java
  src/main/java/com/fc/toy_project2/domain/trip/entity/Trip.java
  src/main/java/com/fc/toy_project2/domain/trip/service/TripService.java
  src/test/java/com/fc/toy_project2/trip/docs/TripRestControllerDocsTest.java
  src/test/java/com/fc/toy_project2/trip/unit/controller/TripRestControllerTest.java
  src/test/java/com/fc/toy_project2/trip/unit/service/TripServiceTest.java
Labels: 🚧refactoring

#20 feat&docs&refactor: entity 관계 설정 변경, docs명 변경 및 주석 및 코드 리펙토링
  src/docs/asciidoc/itinerary/itinerary-api.adoc
  src/main/java/com/fc/toy_project2/domain/itinerary/controller/ItineraryGetDeleteController.java
  src/main/java/com/fc/toy_project2/domain/itinerary/dto/response/AccommodationResponseDTO.java
  src/main/java/com/fc/toy_project2/domain/itinerary/dto/response/ItineraryDeleteResponseDTO.java
  src/main/java/com/fc/toy_project2/domain/itinerary/dto/response/TransportationResponseDTO.java
  src/main/java/com/fc/toy_project2/domain/itinerary/dto/response/VisitResponseDTO.java
  src/main/java/com/fc/toy_project2/domain/itinerary/entity/Accommodation.java
  src/main/java/com/fc/toy_project2/domain/itinerary/entity/Itinerary.java
  src/main/java/com/fc/toy_project2/domain/itinerary/entity/Transportation.java
  src/main/java/com/fc/toy_project2/domain/itinerary/entity/Visit.java
  src/main/java/com/fc/toy_project2/domain/itinerary/repository/ItineraryRepository.java
  src/main/java/com/fc/toy_project2/domain/itinerary/service/ItineraryGetDeleteService.java
  src/main/java/com/fc/toy_project2/domain/trip/service/TripService.java
  src/test/java/com/fc/toy_project2/itinerary/docs/ItineraryRestControllerDocsTest.java
  src/test/java/com/fc/toy_project2/itinerary/unit/controller/ItineraryRestControllerTest.java
  src/test/java/com/fc/toy_project2/itinerary/unit/service/ItineraryServiceTest.java
  src/test/resources/application.yaml
Labels: 📚document, 🛠️feature, 🚧refactoring

#23 fix: URI 변경 및 Id를 itineraryId로 변경
  src/main/java/com/fc/toy_project2/domain/itinerary/controller/ItineraryGetDeleteController.java
  src/main/java/com/fc/toy_project2/domain/itinerary/dto/response/AccommodationResponseDTO.java
  src/main/java/com/fc/toy_project2/domain/itinerary/dto/response/TransportationResponseDTO.java
  src/main/java/com/fc/toy_project2/domain/itinerary/dto/response/VisitResponseDTO.java
  src/main/java/com/fc/toy_project2/domain/itinerary/service/ItineraryGetDeleteService.java
  src/test/java/com/fc/toy_project2/itinerary/docs/ItineraryRestControllerDocsTest.java
  src/test/java/com/fc/toy_project2/itinerary/unit/controller/ItineraryRestControllerTest.java
  src/test/java/com/fc/toy_project2/itinerary/unit/service/ItineraryServiceTest.java
Labels: 🚧refactoring

#24 Itinerary type 착오로 인한 버그 수정
  src/main/java/com/fc/toy_project2/domain/trip/service/TripService.java
Labels: 🧑🏻‍🔧fix

#25 feat: itineraryName 추가
  src/main/java/com/fc/toy_project2/domain/itinerary/dto/response/AccommodationResponseDTO.java
  src/main/java/com/fc/toy_project2/domain/itinerary/dto/response/TransportationResponseDTO.java
  src/main/java/com/fc/toy_project2/domain/itinerary/dto/response/VisitResponseDTO.java
  src/main/java/com/fc/toy_project2/domain/itinerary/entity/Itinerary.java
  src/main/java/com/fc/toy_project2/domain/itinerary/service/ItineraryGetDeleteService.java
  src/test/java/com/fc/toy_project2/itinerary/docs/ItineraryRestControllerDocsTest.java
  src/test/java/com/fc/toy_project2/itinerary/unit/controller/ItineraryRestControllerTest.java
  src/test/java/com/fc/toy_project2/itinerary/unit/service/ItineraryServiceTest.java
Labels: 🛠️feature

#26 여행 조회 시 여정 정보를 포함하여 응답하도록 수정
  src/docs/asciidoc/index.adoc
  src/main/java/com/fc/toy_project2/domain/trip/controller/TripRestController.java
  src/main/java/com/fc/toy_project2/domain/trip/dto/response/GetTripResponseDTO.java
  src/main/java/com/fc/toy_project2/domain/trip/dto/response/GetTripsResponseDTO.java
  src/main/java/com/fc/toy_project2/domain/trip/dto/response/ItineraryInfoDTO.java
  src/main/java/com/fc/toy_project2/domain/trip/entity/Trip.java
  src/main/java/com/fc/toy_project2/domain/trip/service/TripService.java
  src/test/java/com/fc/toy_project2/trip/docs/TripRestControllerDocsTest.java
  src/test/java/com/fc/toy_project2/trip/unit/controller/TripRestControllerTest.java
  src/test/java/com/fc/toy_project2/trip/unit/service/TripServiceTest.java
Labels: 🛠️feature, 🚧refactoring

#27 여정 등록 및 수정 기능 구현 + 글로벌 형변환 메서드 추가
  src/docs/asciidoc/itinerary/itinerary-api.adoc
  src/main/java/com/fc/toy_project2/domain/itinerary/controller/ItineraryGetDeleteController.java
  src/main/java/com/fc/toy_project2/domain/itinerary/controller/ItineraryRestController.java
  src/main/java/com/fc/toy_project2/domain/itinerary/controller/ItineraryRestControllerAdvice.java
  src/main/java/com/fc/toy_project2/domain/itinerary/dto/request/AccommodationCreateRequestDTO.java
  src/main/java/com/fc/toy_project2/domain/itinerary/dto/request/AccommodationUpdateRequestDTO.java
  src/main/java/com/fc/toy_project2/domain/itinerary/dto/request/TransportationCreateRequestDTO.java
  src/main/java/com/fc/toy_project2/domain/itinerary/dto/request/TransportationUpdateRequestDTO.java
  src/main/java/com/fc/toy_project2/domain/itinerary/dto/request/VisitCreateRequestDTO.java
  src/main/java/com/fc/toy_project2/domain/itinerary/dto/request/VisitUpdateRequestDTO.java
  src/main/java/com/fc/toy_project2/domain/itinerary/entity/Itinerary.java
  src/main/java/com/fc/toy_project2/domain/itinerary/exception/InvalidItineraryException.java
  src/main/java/com/fc/toy_project2/domain/itinerary/service/ItineraryGetDeleteService.java
  src/main/java/com/fc/toy_project2/domain/itinerary/service/ItineraryService.java
  src/main/java/com/fc/toy_project2/domain/trip/entity/Trip.java
  src/main/java/com/fc/toy_project2/global/exception/InvalidDateFormatException.java
  src/main/java/com/fc/toy_project2/global/util/DateTypeFormatterUtil.java
  src/test/java/com/fc/toy_project2/global/util/DateTypeFormatterUtilTest.java
  src/test/java/com/fc/toy_project2/itinerary/docs/ItineraryRestControllerDocsTest.java
  src/test/java/com/fc/toy_project2/itinerary/unit/controller/ItineraryRestControllerTest.java
  src/test/java/com/fc/toy_project2/itinerary/unit/service/ItineraryServiceTest.java
Labels: 📚document, 🛠️feature, 🚧refactoring

#28 여정 등록, 조회, 수정 수정
  src/main/java/com/fc/toy_project2/domain/itinerary/service/ItineraryService.java
  src/test/java/com/fc/toy_project2/itinerary/docs/ItineraryRestControllerDocsTest.java
  src/test/java/com/fc/toy_project2/itinerary/unit/controller/ItineraryRestControllerTest.java
  src/test/java/com/fc/toy_project2/itinerary/unit/service/ItineraryServiceTest.java
Labels: 🧑🏻‍🔧fix

#29 테스트 데이터 수정
  src/test/java/com/fc/toy_project2/trip/docs/TripRestControllerDocsTest.java
  src/test/java/com/fc/toy_project2/trip/unit/controller/TripRestControllerTest.java
Labels: 🧑🏻‍🔧fix

#30 체류 등록 시 타입이 2로 저장되도록 수정
  src/main/java/com/fc/toy_project2/domain/itinerary/service/ItineraryService.java
Labels: 🧑🏻‍🔧fix

#31 여정 조회 및 특정 여행 조회 수정
  src/main/java/com/fc/toy_project2/domain/itinerary/service/ItineraryService.java
  src/main/java/com/fc/toy_project2/domain/trip/entity/Trip.java
Labels: 🧑🏻‍🔧fix

#32 리드미 수정
  README.md
  src/main/resources/image/api_docs_index.png
  src/main/resources/image/api_docs_itinerary.png
  src/main/resources/image/api_docs_trip.png
  src/main/resources/image/console.png
  src/main/resources/image/db_itinerary.png
  src/main/resources/image/db_trip.png
  src/main/resources/image/erd.png
  src/test/java/com/fc/toy_project2/docs/SampleController.java
Labels: 📚document

#33 docs: README.md 목차 수정
  README.md
Labels: 📚document

#34 엔터티 싱글 테이블 상속 전략 적용
  src/main/java/com/fc/toy_project2/domain/itinerary/entity/Accommodation.java
  src/main/java/com/fc/toy_project2/domain/itinerary/entity/Itinerary.java
  src/main/java/com/fc/toy_project2/domain/itinerary/entity/Transportation.java
  src/main/java/com/fc/toy_project2/domain/itinerary/entity/Visit.java
  src/main/java/com/fc/toy_project2/domain/itinerary/repository/AccommodationRepository.java
  src/main/java/com/fc/toy_project2/domain/itinerary/repository/TransportationRepository.java
  src/main/java/com/fc/toy_project2/domain/itinerary/repository/VisitRepository.java
  src/main/java/com/fc/toy_project2/domain/itinerary/service/ItineraryService.java
  src/main/java/com/fc/toy_project2/domain/trip/entity/Trip.java
  src/main/java/com/fc/toy_project2/domain/trip/service/TripService.java
  src/test/java/com/fc/toy_project2/itinerary/unit/service/ItineraryServiceTest.java
  src/test/java/com/fc/toy_project2/trip/unit/controller/TripRestControllerTest.java
Labels: 🚧refactoring
